(() => {
  //If you want to add more images, add the link alt and URL image URL in the array list below.
  const images_list = [
    {
      url: "resources/Slide/slide (1).jpg",
      alt: "06437N73R392TP3.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (3).jpg",
      alt: "08597EL5BYZITTF.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (4).jpg",
      alt: "11618_3TOIY3FW6.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (2).jpg",
      alt: "07697Q4AT2NP79H.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (5).jpg",
      alt: "14385U88512XN1F.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (6).jpg",
      alt: "17435ZEE7VYCRCG.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (7).jpg",
      alt: "1590086K6U6MTZN.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (8).jpg",
      alt: "234179QE8SN6V16.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (10).jpg",
      alt: "25496M87YFMYDQS.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (11).jpg",
      alt: "19248U4M8EY4PER.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (9).jpg",
      alt: "19248U4M8EY4PER.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (13).jpg",
      alt: "19248U4M8EY4PER.jpg",
      link: "",
    },
    {
      url: "resources/Slide/slide (12).jpg",
      alt: "19248U4M8EY4PER.jpg",
      link: "",
    },
  ];

  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
  let slider_id = document.querySelector("#slider-1");

  // append all images
  let images_div = "";
  for (let i = 0; i < images_list.length; i++) {
    // if no link without href="" tag
    let href =
      images_list[i].link == "" ? "" : ' href="' + images_list[i].link + '"';
    images_div +=
      "<a" +
      href +
      ' class="slides animated"' +
      (i === 0 ? ' style="display:flex"' : "") +
      ">" +
      '<img src="' +
      images_list[i].url +
      '" alt="' +
      images_list[i].alt +
      '">' +
      "</a>";
  }
  slider_id.querySelector(".slider-body").innerHTML = images_div;
  let slide_index = 0;

  const images = slider_id.querySelectorAll(".slides");
  const showSlides = () => {
    if (slide_index > images.length - 1) {
      slide_index = 0;
    }
    if (slide_index < 0) {
      slide_index = images.length - 1;
    }
    for (let i = 0; i < images.length; i++) {
      images[i].style.display = "none";
      if (i == slide_index) {
        images[i].style.display = "flex";
      }
    }
  };

  // auto play
  setInterval(() => {
    slide_index++;
    showSlides();
  }, 6000);
})();